services:
  app:
    build: .
    container_name: proyecto_motos_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: taller_mecanico   
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: proyecto_motos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taller_mecanico  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
